<?php

namespace UKMNorge\EconomyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetRepository extends EntityRepository
{
	public function findAll()
    {
		$query = $this->createQueryBuilder('b')
						->where('b.deletedSince > :now')
						->orWhere('b.deletedSince IS NULL')
						->orWhere('b.deletedSince = 0')
						->orderBy('b.code', 'ASC')
						->setParameters(array('now' => date('Y') ));
		
		return $query->getQuery()->getResult();
    }
}
