<?php

namespace UKMNorge\EconomyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BudgetAllocatedAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetAllocatedAmountRepository extends EntityRepository
{
	
	public function getTotalByBudget( $budget, $year ) {
	    $q = $this->createQueryBuilder('e')
	        ->addSelect('SUM(e.amount) AS total')
	        ->where('e.budget = :budget')
	        ->whereAnd('e.year = :year')
	        ->setParameter(array('budget','year'), array($budget,$year))
	        ->getQuery();
	        
	    $result = $q->getSingleResult();
	    return $result['total'];
	}
}
