<?php

namespace UKMNorge\EconomyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AllocatedAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubProjectAllocatedAmountRepository extends EntityRepository
{
	
	public function getTotalByBudget( $budget, $year ) {
		$q = $this->createQueryBuilder('e')
	        ->addSelect('SUM(e.amount) AS total')
	        ->where('e.budget = :budget AND e.year = :year')
	        ->setParameter('budget', $budget)
	        ->setParameter('year', $year)
	        ->getQuery();
	        
	    $result = $q->getSingleResult();
	    return $result['total'];

	}
}
