<?php

namespace UKMNorge\EconomyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use UKMNorge\EconomyBundle\Entity\Project;


/**
 * SubProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubProjectRepository extends EntityRepository
{
	public function findAll() {
		return $this->findBy(array(), array('name' => 'ASC'));
	}
	
	public function findByProject(Project $project)
    {
		$em = $this->getEntityManager();
		$query = $em->createQuery('SELECT s
									FROM UKMecoBundle:SubProject s
									WHERE s.project = :project
									AND (s.deletedSince > :now OR s.deletedSince IS NULL OR s.deletedSince = 0)
									ORDER BY s.name ASC'
								   )->setParameter('project', $project->getId())
								   ->setParameter('now', date('Y'));
		return $query->getResult();
    }
}
