<?php

namespace UKMNorge\EconomyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use DateTime;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
	public function getAllBySubProject( $subProject, $year ) {
		$q = $this->createQueryBuilder('e')
				  ->select('e')
				  ->where('e.subProject = :subProject')
				  ->andWhere($this->createQueryBuilder('e')->expr()->between('e.date', ':date_from', ':date_to'))
				  ->setParameter('subProject', $subProject->getId())
				  ->setParameter('date_from', new DateTime(date('Y').'-01-01'))
				  ->setParameter('date_to', new DateTime(date('Y').'-12-31'))
				  ->getQuery();
				  
		$result = $q->getResult();
		return $result;
	}
	
	public function getTotalByBudget( $budget, $year ) {
	    $q = $this->createQueryBuilder('e')
	        ->addSelect('SUM(e.amount) AS total')
	        ->where('e.budget = :budget')
			->andWhere($this->createQueryBuilder('e')->expr()->between('e.date', ':date_from', ':date_to'))
	        ->setParameter('budget', $budget->getId())
	        ->setParameter('date_from', new DateTime(date('Y').'-01-01'))
	        ->setParameter('date_to', new DateTime(date('Y').'-12-31'))
	        ->getQuery();
	        
	    $result = $q->getSingleResult();
	    return $result['total'];
	}

	public function getTotalByProject( $project, $year ) {
	    $q = $this->createQueryBuilder('e')
	        ->addSelect('SUM(e.amount) AS total')
	        ->where('e.project = :project')
			->andWhere($this->createQueryBuilder('e')->expr()->between('e.date', ':date_from', ':date_to'))
	        ->setParameter('project', $project->getId())
	        ->setParameter('date_from', new DateTime(date('Y').'-01-01'))
	        ->setParameter('date_to', new DateTime(date('Y').'-12-31'))
	        ->getQuery();
	        
	    $result = $q->getSingleResult();
	    return $result['total'];
	}

	public function getTotalBySubProject( $subProject, $year ) {
	    $q = $this->createQueryBuilder('e')
	        ->addSelect('SUM(e.amount) AS total')
	        ->where('e.subProject = :subProject')
			->andWhere($this->createQueryBuilder('e')->expr()->between('e.date', ':date_from', ':date_to'))
	        ->setParameter('subProject', $subProject->getId())
	        ->setParameter('date_from', new DateTime(date('Y').'-01-01'))
	        ->setParameter('date_to', new DateTime(date('Y').'-12-31'))
	        ->getQuery();
	        
	    $result = $q->getSingleResult();
	    return $result['total'];
	}

}
